include /home/aaron/.cache/wal/colors-kitty.conf
listen_on unix:@mykitty
allow_remote_control yes
window_padding_width 20
adjust_line_height 4
sync_to_monitor yes
#input_delay 0
#repaint_delay 16
background_opacity         0.87
#force_ltr yes
font_family      Iosevka term
bold_font        Iosevka term heavy
italic_font      Iosevka term italic
bold_italic_font Iosevka term italic
inactive_text_alpha 0.7	
dim_opacity 0.5
enable_wayland_window=true
scrollback_lines 200
scrollback_pager_history_max_size 10
scrollbar_width 0
max_image_bytes 16214400
enable_layouts no
#gpu_backend=cpu
draw_delay=0.02
animation_duration 0.0
vsync=false
confirm_os_window_close 0
font_size 12.5
#foreground          #e3e3e3
background          #15150a
#cursor             #2f3539

#active_tab_foreground     #e1e3f2
#active_tab_background     #181F33
#inactive_tab_foreground   #e1e3f2
#inactive_tab_background   #fdfcfd

#active_border_color   #181F33
#inactive_border_color #fdfcfd
#bell_border_color     #9DA3AE

# black
#color0       #0d0d0d
#color8       #0d0d0d

# red
#color1       #d29096
#color9       #d29096

# green
#color2       #c7dddd
#color10      #c7dddd

# yellow
#color3       #f5e5c5
#color11      #f5e5c5

# blue
#color4       #81a1c1
#color12      #81a1c1

# purple
#color5       #d9c6d6
#color13      #d9c6d6

# pink
#color6       #ffe0ee
#color14      #ffe0ee

# white
#color7       #e1e3f2
#color15      #e1e3f2
disable_ligatures yes
scrollback_lines 0
enable_shell_integration yes
